### ISSUE TITLE
Failed to load resource: the server responded with a status of 429 ()

### ISSUE THREAD

**Issue by xueandyue** [14790897/auto-read-liunxdo#12]
"Failed to load resource: the server responded with a status of 429"这个提示正常吗？
下面是具体的日志：

登录操作
PAGE LOG: JSHandle@node
PAGE LOG: Login button clicked.
PAGE LOG: Autofocus processing was blocked because a document already has a focused element.
PAGE LOG: ℹ️ Discourse v3.2.1 — https://github.com/discourse/discourse/commits/5abd8e9bb0 — Ember v5.5.0
找到avatarImg，登录成功
Page error: Cannot read properties of null (reading 'appendChild')
PAGE LOG: ℹ️ Discourse v3.2.1 — https://github.com/discourse/discourse/commits/5abd8e9bb0 — Ember v5.5.0
PAGE LOG: 脚本第一次运行，执行初始化操作...
PAGE LOG: 执行了初始数据更新操作
PAGE LOG: autoRead true autoLikeEnabled true
PAGE LOG: 执行正常的滚动和检查逻辑
PAGE LOG: 已滚动到底部
Page error: Cannot read properties of null (reading 'appendChild')
PAGE LOG: ℹ️ Discourse v3.2.1 — https://github.com/discourse/discourse/commits/5abd8e9bb0 — Ember v5.5.0
PAGE LOG: 脚本非第一次运行
PAGE LOG: autoRead true autoLikeEnabled true
PAGE LOG: 正在导航到下一个话题
PAGE LOG: Found link: https://linux.do/t/topic/6022
Page error: Cannot read properties of null (reading 'appendChild')
PAGE LOG: ℹ️ Discourse v3.2.1 — https://github.com/discourse/discourse/commits/5abd8e9bb0 — Ember v5.5.0
PAGE LOG: 脚本非第一次运行
PAGE LOG: autoRead true autoLikeEnabled true
PAGE LOG: 执行正常的滚动和检查逻辑
PAGE LOG: Clicked like button 1
PAGE LOG: Clicked like button 2
PAGE LOG: Clicked like button 3
PAGE LOG: Clicked like button 4
PAGE LOG: Clicked like button 5
PAGE LOG: Clicked like button 6
PAGE LOG: Clicked like button 7
PAGE LOG: Clicked like button 8
PAGE LOG: Clicked like button 9
PAGE LOG: Clicked like button 10
PAGE LOG: Clicked like button 11
PAGE LOG: Failed to load resource: the server responded with a status of 429 ()
PAGE LOG: Clicked like button 12
PAGE LOG: Failed to load resource: the server responded with a status of 429 ()
PAGE LOG: Clicked like button 13
PAGE LOG: Failed to load resource: the server responded with a status of 429 ()
PAGE LOG: Clicked like button 14
PAGE LOG: Failed to load resource: the server responded with a status of 429 ()
Retrying now...
PAGE LOG: Clicked like button 15
Page error: Cannot read properties of null (reading 'appendChild')
PAGE LOG: ℹ️ Discourse v3.2.1 — https://github.com/discourse/discourse/commits/5abd8e9bb0 — Ember v5.5.0
PAGE LOG: 脚本非第一次运行
PAGE LOG: autoRead true autoLikeEnabled false
PAGE LOG: 执行正常的滚动和检查逻辑
PAGE LOG: Failed to load resource: the server responded with a status of 429 ()

**Comment by 14790897** [comment]
我也不知道，我觉得能阅读就正常

**Comment by 14790897** [comment]
正常的

**Comment by xueandyue** [comment]
> 正常的

谢谢！
