### ISSUE TITLE
非workflow模式下，如何指定阅读时间？

### ISSUE THREAD

**Issue by sk163** [14790897/auto-read-liunxdo#13]
请教下，如果使用非github action的workflow模式下，如何指定阅读时间？用docker的方式，可以指定阅读时长么？还是说docker方式就是一直阅读，直到出现429错误自己退出？现在是在操作系统里的cron配置了定时做docker-compose down

**Comment by 14790897** [comment]
docker是一直读，429不会退出除非手动停止

**Comment by 14790897** [comment]
目前没有指定时间功能

**Comment by sk163** [comment]
好嘞，多谢多谢~要是docker的环境变量里能设定每次阅读的间隔时间就好了，这样应该能减少429错误的频率

**Comment by 14790897** [comment]
429一般是点赞太多，这个基本没有影响

**Comment by sk163** [comment]
> 429一般是点赞太多，这个基本没有影响

[抱拳][抱拳]
