### ISSUE TITLE
频繁出现这个错误提示是什么问题呢

### ISSUE THREAD

**Issue by lostme01** [14790897/auto-read-liunxdo#14]
Page error: Cannot read properties of null (reading 'appendChild')

**Comment by lostme01** [comment]
[docker-compose.yml](https://github.com/14790897/auto-read-liunxdo/blob/main/docker-compose.yml)

使用的这个 docker compose 搭建的

**Comment by 14790897** [comment]
正常情况，油猴脚本有点不适配puppeteer，不影响

**Comment by lostme01** [comment]
> 正常情况，油猴脚本有点不适配puppeteer，不影响

哦 。还可以优化吗？大佬

**Comment by 14790897** [comment]
正常的

**Comment by lostme01** [comment]
![image](https://github.com/14790897/auto-read-liunxdo/assets/28937468/201c14a2-ffdc-4859-b1d7-b11aa00784a6)

**Comment by 14790897** [comment]
这个错误我也不知道
