### ISSUE TITLE
PAGE LOG: No link with the specified format was found.

### ISSUE THREAD

**Issue by cikichen** [14790897/auto-read-liunxdo#16]
PAGE LOG: No link with the specified format was found.
PAGE LOG: No link with the specified format was found.
PAGE LOG: No link with the specified format was found.
PAGE LOG: No link with the specified format was found.
PAGE LOG: No link with the specified format was found.
PAGE LOG: No link with the specified format was found.
PAGE LOG: No link with the specified format was found.
PAGE LOG: No link with the specified format was found.
PAGE LOG: No link with the specified format was found.
PAGE LOG: No link with the specified format was found.
PAGE LOG: No link with the specified format was found.
PAGE LOG: No link with the specified format was found.
PAGE LOG: No link with the specified format was found.
PAGE LOG: No link with the specified format was found.
PAGE LOG: No link with the specified format was found.
PAGE LOG: No link with the specified format was found.
PAGE LOG: No link with the specified format was found.
PAGE LOG: No link with the specified format was found.
PAGE LOG: No link with the specified format was found.
PAGE LOG: No link with the specified format was found.
PAGE LOG: No link with the specified format was found.
PAGE LOG: No link with the specified format was found.
PAGE LOG: No link with the specified format was found.
PAGE LOG: No link with the specified format was found.
PAGE LOG: No link with the specified format was found.
PAGE LOG: No link with the specified format was found.
PAGE LOG: No link with the specified format was found.
PAGE LOG: No link with the specified format was found.
PAGE LOG: No link with the specified format was found.
PAGE LOG: No link with the specified format was found.
PAGE LOG: No link with the specified format was found.
PAGE LOG: No link with the specified format was found.
PAGE LOG: No link with the specified format was found.
PAGE LOG: No link with the specified format was found.
PAGE LOG: No link with the specified format was found.
PAGE LOG: No link with the specified format was found.
PAGE LOG: No link with the specified format was found.
PAGE LOG: No link with the specified format was found.
PAGE LOG: No link with the specified format was found.
PAGE LOG: No link with the specified format was found.
PAGE LOG: No link with the specified format was found.
PAGE LOG: No link with the specified format was found.
PAGE LOG: No link with the specified format was found.
PAGE LOG: No link with the specified format was found.
PAGE LOG: No link with the specified format was found.
PAGE LOG: No link with the specified format was found.
PAGE LOG: No link with the specified format was found.
PAGE LOG: No link with the specified format was found.
PAGE LOG: No link with the specified format was found.
PAGE LOG: No link with the specified format was found.
PAGE LOG: No link with the specified format was found.

一直刷这个正常吗？

**Comment by 14790897** [comment]
正常，因为文章都读完了，找不到新的

Simon ***@***.***> 于 2024年4月20日周六 下午8:48写道：

**Comment by 14790897** [comment]
能不能帮我在readme补充这个问题，提个pr

**Comment by cikichen** [comment]
> 能不能帮我在readme补充这个问题，提个pr

ok
