### ISSUE TITLE
github workflow出现问题

### ISSUE THREAD

**Issue by heurainbow** [14790897/auto-read-liunxdo#21]
![image](https://github.com/14790897/auto-read-liunxdo/assets/6753276/c8b14185-2ebb-4e53-aab9-f7170a879d5f)

部署github action后log出现这样的情况

**Comment by 14790897** [comment]
这个可能与网络有关，我有时也遇到，如果是自己的电脑就没这个问题

**Comment by 14790897** [comment]
要不试试在.env中把用户名密码重复几次，这样可以多尝试几次

**Comment by heurainbow** [comment]
重复几次也不行。 我用docker运行也会报这个错误。美国的vps。
我看这个错误好像要在执行脚本的时候加上'unsafe-inline'

**Comment by heurainbow** [comment]
![image](https://github.com/14790897/auto-read-liunxdo/assets/6753276/9217a649-795d-44c1-855e-c071796ed319)
这个是docker运行的log

**Comment by 14790897** [comment]
> ![image](https://private-user-images.githubusercontent.com/6753276/328353792-9217a649-795d-44c1-855e-c071796ed319.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUwNDU4NzUsIm5iZiI6MTcxNTA0NTU3NSwicGF0aCI6Ii82NzUzMjc2LzMyODM1Mzc5Mi05MjE3YTY0OS03OTVkLTQ0YzEtODU1ZS1jMDcxNzk2ZWQzMTkucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUwNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MDdUMDEzMjU1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MmNlOGFjNjhjN2E4YjA3ZGYwOTBhZTQ4NzExMzIxYmI5ODAzZmQ5ODJjZTE1ODI3NmNjNzA2ZDk2OGI2MGFhNCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.lVVlX5kCzVL1gXlQEOEBqu_4c46T2HB6T4OY5hI5geo) 这个是docker运行的log

这个错误是这个网站本身自带的，现在手动打开这个网站就会报这个错误

**Comment by heurainbow** [comment]
用油猴脚本目前看没问题

**Comment by 14790897** [comment]
![image](https://github.com/14790897/auto-read-liunxdo/assets/121866954/ca428cef-7275-4980-a463-3f09638db8f1)

**Comment by heurainbow** [comment]
那是不是docker和github workflow暂时用不了了

**Comment by 14790897** [comment]
没有影响
