### ISSUE TITLE
请问这是怎么回事？

### ISSUE THREAD

**Issue by JerryXu09** [14790897/auto-read-liunxdo#24]
卡在这里4分多钟了，没有反应了，是我的配置不对吗？
![Scheduled Node js CI · JerryXu09auto-read-liunxd…](https://github.com/14790897/auto-read-liunxdo/assets/132908192/052d9700-08eb-4c6a-9d83-c0e03ec60ad7)
如何解决？求解答

**Comment by 14790897** [comment]
这个可能与网络有关，我有时也遇到，如果是自己的电脑运行就没这个问题

要不试试在.env中把用户名密码重复几次，这样可以多尝试几次

**Comment by lifenglsf** [comment]
我一开始actions的用户名和密码配置错了就是这个情况，用户名和密码要配置成Repository的，部署environment的
