### ISSUE TITLE
好像不能自动增加访问天数

### ISSUE THREAD

**Issue by lifenglsf** [14790897/auto-read-liunxdo#26]
![image](https://github.com/14790897/auto-read-liunxdo/assets/1817560/bc743951-7004-48e7-8c2b-aac0c8f4bacd)
actions实际执行的时间，
![image](https://github.com/14790897/auto-read-liunxdo/assets/1817560/757d7e47-fcf4-4323-ae7a-3e0c2e993ff5)
昨天就是35天，执行了访问发现还是35天，一个不会是始皇没有更新吧，晚点再看看

**Comment by 14790897** [comment]
执行时间设置久一点

**Comment by lifenglsf** [comment]
还要观察观察，貌似手动访问了也没有加，估计是前面有段时间周末断了的原因，现在是默认的10分钟。还想只刷固定数量的帖子然后结束，但是改来改去程序都没有自动结束

**Comment by lifenglsf** [comment]
是断登的原因
