### ISSUE TITLE
[建议]加入插件支持

### ISSUE THREAD

**Issue by ghotm** [14790897/auto-read-liunxdo#31]
触发登陆按钮后发现request中有cloudflare的请求,应该是触发了人机验证,如果加入插件是否能更好的解决人机验证的问题?
参考资料:
https://anti-captcha.com/zh/apidoc/articles/how-to-integrate-the-plugin
https://github.com/rucaptcha/2captcha-solver?tab=readme-ov-file
https://github.com/NopeCHALLC/nopecha-extension

**Comment by 14790897** [comment]
https://github.com/14790897/auto-read-liunxdo/releases/tag/v1.3.0
解决了
