### ISSUE TITLE
过不了cf验证了

### ISSUE THREAD

**Issue by cikichen** [14790897/auto-read-liunxdo#33]
PAGE LOG: Request for the Private Access Token challenge.
PAGE LOG: The next request for the Private Access Token challenge may return a 401 and show a warning in console.
PAGE LOG: console.groupEnd
Page error: TurnstileError: [Cloudflare Turnstile] Error: 600010.
PAGE LOG: 
PAGE LOG: JSHandle@error
PAGE LOG: JSHandle@regexp
PAGE LOG: JSHandle@regexp
PAGE LOG: JSHandle@function
PAGE LOG: JSHandle@function
PAGE LOG: JSHandle@node
PAGE LOG: JSHandle@node
PAGE LOG: : 1
PAGE LOG: : 1
PAGE LOG: %c%d font-size:0;color:transparent NaN
PAGE LOG: %c%d font-size:0;color:transparent NaN
PAGE LOG:  JSHandle@error
PAGE LOG:  JSHandle@error
PAGE LOG: %c%d font-size:0;color:transparent JSHandle@error
PAGE LOG: %c%d font-size:0;color:transparent JSHandle@error
PAGE LOG: %c%d font-size:0;color:transparent NaN
PAGE LOG: %c%d font-size:0;color:transparent NaN
PAGE LOG: %c%d font-size:0;color:transparent NaN
PAGE LOG: %c%d font-size:0;color:transparent NaN
PAGE LOG: %c%d font-size:0;color:transparent NaN
PAGE LOG: %c%d font-size:0;color:transparent NaN
PAGE LOG: %c%d font-size:0;color:transparent JSHandle@error
PAGE LOG: %c%d font-size:0;color:transparent JSHandle@error
PAGE LOG: %c%d font-size:0;color:transparent NaN
PAGE LOG: %c%d font-size:0;color:transparent NaN
PAGE LOG: %c%d font-size:0;color:transparent NaN
PAGE LOG: %c%d font-size:0;color:transparent NaN
PAGE LOG: console.groupEnd
PAGE LOG: Request for the Private Access Token challenge.
PAGE LOG: The next request for the Private Access Token challenge may return a 401 and show a warning in console.
PAGE LOG: console.groupEnd
Page error: TurnstileError: [Cloudflare Turnstile] Error: 600010.

**Comment by cikichen** [comment]
action有问题，取消会失败

**Comment by Jamessmith8216** [comment]
Linux DO 站點，NEO 開了CF 的最新的防BOT WAF.... 這腳本好像不能用了，

**Comment by 14790897** [comment]
https://linux.do/t/topic/131373  还在研究中
