### ISSUE TITLE
Failed to load resource: the server responded with a status of 429 

### ISSUE THREAD

**Issue by fengyaocheng** [14790897/auto-read-liunxdo#39]
Using .env file to supply config environment variables, you can create a .env.local file to overwrite defaults, it doesn't upload to git
页面标题： LINUX DO - 新的理想型社区
登录操作
PAGE LOG: Login button clicked.
PAGE LOG: Autofocus processing was blocked because a document already has a focused element.
Page error: Failed to execute 'getValue' on 'CookieDeprecationLabel': Illegal invocation
PAGE LOG: ℹ️ Discourse v3.3.0 — https://github.com/discourse/discourse/commits/ac30a7[9](https://github.com/fengyaocheng/auto-read-liunxdo/actions/runs/10284825125/job/28461687764#step:6:10)8f0 — Ember v5.5.0
找到avatarImg，登录成功
PAGE LOG: 当前BASE_URL是: ***
PAGE LOG: 脚本正在运行在: ***
PAGE LOG: Initial clickCounter: 0
Page error: Failed to execute 'getValue' on 'CookieDeprecationLabel': Illegal invocation
PAGE LOG: ℹ️ Discourse v3.3.0 — https://github.com/discourse/discourse/commits/ac30a798f0 — Ember v5.5.0
PAGE LOG: 脚本第一次运行，执行初始化操作...
PAGE LOG: 执行了初始数据更新操作
PAGE LOG: autoRead true autoLikeEnabled true
PAGE LOG: 执行正常的滚动和检查逻辑
PAGE LOG: Initial clickCounter: 0
PAGE LOG: Found 20 buttons.
PAGE LOG: Clicked like button 4
PAGE LOG: clickCounter: 1
PAGE LOG: 已滚动到底部
PAGE LOG: 当前BASE_URL是: ***
PAGE LOG: 脚本正在运行在: ***
PAGE LOG: Initial clickCounter: 1
Page error: Failed to execute 'getValue' on 'CookieDeprecationLabel': Illegal invocation
PAGE LOG: ℹ️ Discourse v3.3.0 — https://github.com/discourse/discourse/commits/ac30a798f0 — Ember v5.5.0
PAGE LOG: 脚本非第一次运行
PAGE LOG: autoRead true autoLikeEnabled true
PAGE LOG: 正在导航到下一个话题
PAGE LOG: Found link: ***/t/topic/171392/15
PAGE LOG: 当前BASE_URL是: ***
PAGE LOG: 脚本正在运行在: ***
PAGE LOG: Initial clickCounter: 1
PAGE LOG: ℹ️ Discourse v3.3.0 — https://github.com/discourse/discourse/commits/ac30a798f0 — Ember v5.5.0
PAGE LOG: ℹ️ Discourse v3.3.0 — https://github.com/discourse/discourse/commits/ac30a798f0 — Ember v5.5.0
Page error: Failed to execute 'getValue' on 'CookieDeprecationLabel': Illegal invocation
PAGE LOG: 脚本非第一次运行
PAGE LOG: autoRead true autoLikeEnabled true
PAGE LOG: 执行正常的滚动和检查逻辑
PAGE LOG: 已滚动到底部
PAGE LOG: Initial clickCounter: 1
PAGE LOG: Found 15 buttons.
PAGE LOG: Clicked like button 1
PAGE LOG: clickCounter: 2
PAGE LOG: 当前BASE_URL是: ***
PAGE LOG: 脚本正在运行在: ***
PAGE LOG: Initial clickCounter: 2
PAGE LOG: ℹ️ Discourse v3.3.0 — https://github.com/discourse/discourse/commits/ac30a798f0 — Ember v5.5.0
PAGE LOG: 脚本非第一次运行
PAGE LOG: autoRead true autoLikeEnabled true
PAGE LOG: 正在导航到下一个话题
Page error: Failed to execute 'getValue' on 'CookieDeprecationLabel': Illegal invocation
PAGE LOG: Found link: ***/t/topic/171369
PAGE LOG: 当前BASE_URL是: ***
PAGE LOG: 脚本正在运行在: ***
PAGE LOG: Initial clickCounter: 2
PAGE LOG: ℹ️ Discourse v3.3.0 — https://github.com/discourse/discourse/commits/ac30a798f0 — Ember v5.5.0
Page error: Failed to execute 'getValue' on 'CookieDeprecationLabel': Illegal invocation
PAGE LOG: 脚本非第一次运行
PAGE LOG: autoRead true autoLikeEnabled true
PAGE LOG: 执行正常的滚动和检查逻辑
PAGE LOG: Initial clickCounter: 2
PAGE LOG: Found 20 buttons.
PAGE LOG: Clicked like button 1
PAGE LOG: clickCounter: 3
PAGE LOG: Clicked like button 2
PAGE LOG: clickCounter: 4
PAGE LOG: Failed to load resource: the server responded with a status of 429 ()
PAGE LOG: Failed to update topic times for topic 171369 due to 429 error
PAGE LOG: Clicked like button 3
PAGE LOG: clickCounter: 5
PAGE LOG: Failed to load resource: the server responded with a status of 429 ()
Retrying now...
PAGE LOG: Clicked like button 4
PAGE LOG: clickCounter: 6
PAGE LOG: Failed to load resource: the server responded with a status of 429 ()
PAGE LOG: Failed to load resource: the server responded with a status of 429 ()
PAGE LOG: Failed to update topic times for topic 171369 due to 429 error
PAGE LOG: Clicked like button 5
PAGE LOG: clickCounter: 7
PAGE LOG: Failed to load resource: the server responded with a status of 429 ()
PAGE LOG: Clicked like button 6
PAGE LOG: clickCounter: 8
PAGE LOG: Clicked like button 7
PAGE LOG: clickCounter: 9
PAGE LOG: Clicked like button 8
PAGE LOG: clickCounter: [10](https://github.com/fengyaocheng/auto-read-liunxdo/actions/runs/10284825125/job/28461687764#step:6:11)
PAGE LOG: Clicked like button 9
PAGE LOG: clickCounter: [11](https://github.com/fengyaocheng/auto-read-liunxdo/actions/runs/10284825125/job/28461687764#step:6:12)
PAGE LOG: Clicked like button 10
PAGE LOG: clickCounter: [12](https://github.com/fengyaocheng/auto-read-liunxdo/actions/runs/10284825125/job/28461687764#step:6:13)
PAGE LOG: Failed to load resource: the server responded with a status of 429 ()
PAGE LOG: Failed to load resource: the server responded with a status of 429 ()
PAGE LOG: Failed to update topic times for topic 17[13](https://github.com/fengyaocheng/auto-read-liunxdo/actions/runs/10284825125/job/28461687764#step:6:14)69 due to 429 error
PAGE LOG: Clicked like button 11
PAGE LOG: clickCounter: 13
PAGE LOG: 已滚动到底部
PAGE LOG: Failed to load resource: the server responded with a status of 429 ()
PAGE LOG: 当前BASE_URL是: ***
PAGE LOG: 脚本正在运行在: ***
PAGE LOG: Initial clickCounter: 13
PAGE LOG: ℹ️ Discourse v3.3.0 — https://github.com/discourse/discourse/commits/ac30a798f0 — Ember v5.5.0
Page error: Failed to execute 'getValue' on 'CookieDeprecationLabel': Illegal invocation
PAGE LOG: 脚本非第一次运行
PAGE LOG: autoRead true autoLikeEnabled false
PAGE LOG: 正在导航到下一个话题
PAGE LOG: Found link: ***/t/topic/5/2109
PAGE LOG: 当前BASE_URL是: ***
PAGE LOG: 脚本正在运行在: ***
PAGE LOG: Initial clickCounter: 13
PAGE LOG: ℹ️ Discourse v3.3.0 — https://github.com/discourse/discourse/commits/ac30a798f0 — Ember v5.5.0
Page error: Failed to execute 'getValue' on 'CookieDeprecationLabel': Illegal invocation
PAGE LOG: 脚本非第一次运行
PAGE LOG: autoRead true autoLikeEnabled false
PAGE LOG: 执行正常的滚动和检查逻辑
PAGE LOG: 已滚动到底部
PAGE LOG: 当前BASE_URL是: ***
PAGE LOG: 脚本正在运行在: ***
PAGE LOG: Initial clickCounter: 13
PAGE LOG: [Report Only] Refused to load the script '***/assets/start-discourse-9f921[14](https://github.com/fengyaocheng/auto-read-liunxdo/actions/runs/10284825125/job/28461687764#step:6:15)2b762fb91207051d0a28e571b9455bab74e7d0e03726024c286cff8d5.js' because it violates the following Content Security Policy directive: "script-src 'none'". Note that 'script-src-elem' was not explicitly set, so 'script-src' is used as a fallback.
PAGE LOG: [Report Only] Refused to load the script '***/assets/browser-update-6f90b23ab8d8bbdca5b58f8c616b7779f50c1315575c80eacccbc30e8bb3c32e.js' because it violates the following Content Security Policy directive: "script-src 'none'". Note that 'script-src-elem' was not explicitly set, so 'script-src' is used as a fallback.
PAGE LOG: [Report Only] Refused to load the script '***/assets/browser-detect-99f42f91bffa8ca1606d62b70bb92f981d83921e78ccdbd3d9538f07007f27ac.js' because it violates the following Content Security Policy directive: "script-src 'none'". Note that 'script-src-elem' was not explicitly set, so 'script-src' is used as a fallback.
PAGE LOG: [Report Only] Refused to load the script '***/assets/vendor.fc515a92f838bfb06405ac3186d67213-d190f217c498848c25a4048fe73ad56cbd28decf7b7eddf1b7ea34d79ee1ee6d.js' because it violates the following Content Security Policy directive: "script-src 'none'". Note that 'script-src-elem' was not explicitly set, so 'script-src' is used as a fallback.
PAGE LOG: [Report Only] Refused to load the script '***/assets/chunk.46db2789b14251f87ab9.d41d8cd9.js' because it violates the following Content Security Policy directive: "script-src 'none'". Note that 'script-src-elem' was not explicitly set, so 'script-src' is used as a fallback.
PAGE LOG: [Report Only] Refused to load the script '***/assets/chunk.74971dc87d0d52475f46.d41d8cd9.js' because it violates the following Content Security Policy directive: "script-src 'none'". Note that 'script-src-elem' was not explicitly set, so 'script-src' is used as a fallback.
PAGE LOG: [Report Only] Refused to load the script '***/assets/plugins/automation_admin-b197f57b3bf59e4dab100cbd4f21cda603b38b3acf22b08b5bd7c6e646547643.js' because it violates the following Content Security Policy directive: "script-src 'none'". Note that 'script-src-elem' was not explicitly set, so 'script-src' is used as a fallback.
PAGE LOG: [Report Only] Refused to load the script '***/assets/plugins/chat-5cce1569af0000a68afc0f6560f13999cf144b55bbf482d0f77f91edc412c8d0.js' because it violates the following Content Security Policy directive: "script-src 'none'". Note that 'script-src-elem' was not explicitly set, so 'script-src' is used as a fallback.
PAGE LOG: [Report Only] Refused to load the script '***/assets/plugins/checklist-36268cbe7ff47fdb7124e259be20f95049b53f5c1785156a0f7e1169105b3569.js' because it violates the following Content Security Policy directive: "script-src 'none'". Note that 'script-src-elem' was not explicitly set, so 'script-src' is used as a fallback.
PAGE LOG: [Report Only] Refused to load the script '***/assets/plugins/discourse-ai-5cd1d4b3a50db64605de4ab5f9085ff1d32b0045ea03fe8b8373d72c4fb846a5.js' because it violates the following Content Security Policy directive: "script-src 'none'". Note that 'script-src-elem' was not explicitly set, so 'script-src' is used as a fallback.
PAGE LOG: [Report Only] Refused to load the script '***/assets/plugins/discourse-ai_admin-8104989c1a2f056da0f1fa5f2c377d4ede698eafed25672b3aec7b456436090c.js' because it violates the following Content Security Policy directive: "script-src 'none'". Note that 'script-src-elem' was not explicitly set, so 'script-src' is used as a fallback.
PAGE LOG: [Report Only] Refused to load the script '***/assets/plugins/discourse-assign-159dd271a7029d191ca40c5217096cb212d68f1cf24aaf07640dafccb54056ad.js' because it violates the following Content Security Policy directive: "script-src 'none'". Note that 'script-src-elem' was not explicitly set, so 'script-src' is used as a fallback.
PAGE LOG: [Report Only] Refused to load the script '***/assets/plugins/discourse-bbcode-3079b7785a470c5508894ce7e21ef4f760f675fb88ea80e2b5a93d9c7b938929.js' because it violates the following Content Security Policy directive: "script-src 'none'". Note that 'script-src-elem' was not explicitly set, so 'script-src' is used as a fallback.
PAGE LOG: [Report Only] Refused to load the script '***/assets/plugins/discourse-bcc-fec19e24df497c1345a14337a46cad25c6070c37fe33788cdaf65384ee4e40b5.js' because it violates the following Content Security Policy directive: "script-src 'none'". Note that 'script-src-elem' was not explicitly set, so 'script-src' is used as a fallback.
PAGE LOG: [Report Only] Refused to load the script '***/assets/plugins/discourse-cakeday-d2ff2c0d18a2f96dd572bce5277c0193e51251aa60b4b3016291efeaf8094f3c.js' because it violates the following Content Security Policy directive: "script-src 'none'". Note that 'script-src-elem' was not explicitly set, so 'script-src' is used as a fallback.
PAGE LOG: [Report Only] Refused to load the script '***/assets/plugins/discourse-category-experts-e71230adcd6a1ea8526c7c83e5f6bba2d79a0d7ac6bca6604199ef1bfde543a8.js' because it violates the following Content Security Policy directive: "script-src 'none'". Note that 'script-src-elem' was not explicitly set, so 'script-src' is used as a fallback.
PAGE LOG: [Report Only] Refused to load the script '***/assets/plugins/discourse-characters-required-84010151d26da327d21c054ec9529309df458b0e6094f10272205bcd967ead41.js' because it violates the following Content Security Policy directive: "script-src 'none'". Note that 'script-src-elem' was not explicitly set, so 'script-src' is used as a fallback.
PAGE LOG: [Report Only] Refused to load the script '***/assets/plugins/discourse-chat-integration-7a472bdf1d99dd15953c35f8f314186f0a1afd2b93a73bc1e3ab081ac88a96bd.js' because it violates the following Content Security Policy directive: "script-src 'none'". Note that 'script-src-elem' was not explicitly set, so 'script-src' is used as a fallback.
PAGE LOG: [Report Only] Refused to load the script '***/assets/plugins/discourse-chat-integration_admin-4bee38498a533496f81802923d47f5cc29c61b470192bbd40aad161458b13251.js' because it violates the following Content Security Policy directive: "script-src 'none'". Note that 'script-src-elem' was not explicitly set, so 'script-src' is used as a fallback.
PAGE LOG: [Report Only] Refused to load the script '***/assets/plugins/discourse-code-review-ca5b030a2907bb21674b00ff37bf71c11f786f2d1025b004d1270a965c79167e.js' because it violates the following Content Security Policy directive: "script-src 'none'". Note that 'script-src-elem' was not explicitly set, so 'script-src' is used as a fallback.
PAGE LOG: [Report Only] Refused to load the script '***/assets/plugins/discourse-details-48148ec534a4c5e9614302186b345123ba1358787c41bc31cbd17231f794fe42.js' because it violates the following Content Security Policy directive: "script-src 'none'". Note that 'script-src-elem' was not explicitly set, so 'script-src' is used as a fallback.
PAGE LOG: [Report Only] Refused to load the script '***/assets/plugins/discourse-docs-b3898e4976f3b2693297e07100c5c640f0ebc2fccf40ae349f699e6f080557dd.js' because it violates the following Content Security Policy directive: "script-src 'none'". Note that 'script-src-elem' was not explicitly set, so 'script-src' is used as a fallback.
PAGE LOG: [Report Only] Refused to load the script '***/assets/plugins/discourse-follow-16015b51714213ce6f0c0476a105b241f1188dd760d06472a3d5bda4b86d885e.js' because it violates the following Content Security Policy directive: "script-src 'none'". Note that 'script-src-elem' was not explicitly set, so 'script-src' is used as a fallback.
PAGE LOG: [Report Only] Refused to load the script '***/assets/plugins/discourse-gamification-9b17aa424f8dac56fca67a802b419b8d9c59642feb497beb5fedf24ec1342936.js' because it violates the following Content Security Policy directive: "script-src 'none'". Note that 'script-src-elem' was not explicitly set, so 'script-src' is used as a fallback.
PAGE LOG: [Report Only] Refused to load the script '***/assets/plugins/discourse-gamification_admin-4fb7513998b868a442fd5e934406a208f2d9a4067ad5cd02d4bc0b7464476afd.js' because it violates the following Content Security Policy directive: "script-src 'none'". Note that 'script-src-elem' was not explicitly set, so 'script-src' is used as a fallback.
PAGE LOG: [Report Only] Refused to load the script '***/assets/plugins/discourse-graphviz-f4a7d4462b162311b1deec252ace6f207ba70962685c5bbb134debb637dbb06d.js' because it violates the following Content Security Policy directive: "script-src 'none'". Note that 'script-src-elem' was not explicitly set, so 'script-src' is used as a fallback.
PAGE LOG: [Report Only] Refused to load the script '***/assets/plugins/discourse-lazy-videos-da6a701d09603c2e1bf81930868aa84af4b9fb58607f1dc8b88dfeb8ed6127f2.js' because it violates the following Content Security Policy directive: "script-src 'none'". Note that 'script-src-elem' was not explicitly set, so 'script-src' is used as a fallback.
PAGE LOG: [Report Only] Refused to load the script '***/assets/plugins/discourse-local-dates-7bdac382dbdbbc30432e1d545f51ca221fc493796065c8ee7de9332d57edd1a1.js' because it violates the following Content Security Policy directive: "script-src 'none'". Note that 'script-src-elem' was not explicitly set, so 'script-src' is used as a fallback.
PAGE LOG: [Report Only] Refused to load the script '***/assets/plugins/discourse-math-334f5819b385286f3bc475492584333b1bda399d22728aaf398f6f8d6e008be5.js' because it violates the following Content Security Policy directive: "script-src 'none'". Note that 'script-src-elem' was not explicitly set, so 'script-src' is used as a fallback.
PAGE LOG: [Report Only] Refused to load the script '***/assets/plugins/discourse-post-voting-85fed95cc6f6c88f33d951e03df62b8e3a497e4b98f9f94f5a5638263ef2839e.js' because it violates the following Content Security Policy directive: "script-src 'none'". Note that 'script-src-elem' was not explicitly set, so 'script-src' is used as a fallback.
PAGE LOG: [Report Only] Refused to load the script '***/assets/plugins/discourse-presence-ffcdcf45164f0338431e09dd3f745f7dccdae8019db90b56830f783c0d7b6fc3.js' because it violates the following Content Security Policy directive: "script-src 'none'". Note that 'script-src-elem' was not explicitly set, so 'script-src' is used as a fallback.
PAGE LOG: [Report Only] Refused to load the script '***/assets/plugins/discourse-reactions-b4348ffefe6ad74dc1d1cfccaebcda7f4014f6c28903df47cfb198e3cec92c8a.js' because it violates the following Content Security Policy directive: "script-src 'none'". Note that 'script-src-elem' was not explicitly set, so 'script-src' is used as a fallback.
PAGE LOG: [Report Only] Refused to load the script '***/assets/plugins/discourse-rss-polling-cff8858a00803693f9fcb8e830ef0bf4b51de826a4825201bc596d330fd9a1e7.js' because it violates the following Content Security Policy directive: "script-src 'none'". Note that 'script-src-elem' was not explicitly set, so 'script-src' is used as a fallback.
PAGE LOG: [Report Only] Refused to load the script '***/assets/plugins/discourse-signatures-be500c5267756498fc52b471230623415d435e606545e678f460e6a370b9d92a.js' because it violates the following Content Security Policy directive: "script-src 'none'". Note that 'script-src-elem' was not explicitly set, so 'script-src' is used as a fallback.
PAGE LOG: [Report Only] Refused to load the script '***/assets/plugins/discourse-solved-0d6bf11d76e369655a95aa3e7d3e6d4e2283974eba848a5a0e5f92a30f2fe014.js' because it violates the following Content Security Policy directive: "script-src 'none'". Note that 'script-src-elem' was not explicitly set, so 'script-src' is used as a fallback.
PAGE LOG: [Report Only] Refused to load the script '***/assets/plugins/discourse-templates-8b14b7a90e6c5306d23be16f4563be66ee8292ea644a910604533546005c1b87.js' because it violates the following Content Security Policy directive: "script-src 'none'". Note that 'script-src-elem' was not explicitly set, so 'script-src' is used as a fallback.
PAGE LOG: [Report Only] Refused to load the script '***/assets/plugins/discourse-topic-voting-1a48a0345166654549e766963d92eff990693210ace4596518b5aa30b09d637a.js' because it violates the following Content Security Policy directive: "script-src 'none'". Note that 'script-src-elem' was not explicitly set, so 'script-src' is used as a fallback.
PAGE LOG: [Report Only] Refused to load the script '***/assets/plugins/docker_manager_admin-f888b3617b7f892ef01d105d0d36d5e2784ea2be973f9885883db0da9a0d1924.js' because it violates the following Content Security Policy directive: "script-src 'none'". Note that 'script-src-elem' was not explicitly set, so 'script-src' is used as a fallback.
PAGE LOG: [Report Only] Refused to load the script '***/assets/plugins/footnote-63a84ac63410c38a9d6344e0d068d181db554623c2c751ba275b273a14ab5eab.js' because it violates the following Content Security Policy directive: "script-src 'none'". Note that 'script-src-elem' was not explicitly set, so 'script-src' is used as a fallback.
PAGE LOG: [Report Only] Refused to load the script '***/assets/plugins/footnote_extra-295b457b90cb18fedfdb544868c494c71842a27c0781d3042fa4fd26589204fa.js' because it violates the following Content Security Policy directive: "script-src 'none'". Note that 'script-src-elem' was not explicitly set, so 'script-src' is used as a fallback.
PAGE LOG: [Report Only] Refused to load the script '***/assets/plugins/poll-047438ab70fc423fb3a3adde9f1c94fcaf17919934649012ea896ccb71434945.js' because it violates the following Content Security Policy directive: "script-src 'none'". Note that 'script-src-elem' was not explicitly set, so 'script-src' is used as a fallback.
PAGE LOG: [Report Only] Refused to load the script '***/assets/plugins/spoiler-alert-398649fb55dd3fbc15869b8bdc345c1a626b23b3bf1627afd9a0994049ad4bf3.js' because it violates the following Content Security Policy directive: "script-src 'none'". Note that 'script-src-elem' was not explicitly set, so 'script-src' is used as a fallback.
PAGE LOG: [Report Only] Refused to load the script '***/assets/locales/zh_CN-325a874b95758bf381ce00ea54b9f8065697be2c0b92488fd5778798d60a6a40.js' because it violates the following Content Security Policy directive: "script-src 'none'". Note that 'script-src-elem' was not explicitly set, so 'script-src' is used as a fallback.
PAGE LOG: [Report Only] Refused to load the script '***/extra-locales/mf?v=7f33dde56118308427d1882ebd0c1916' because it violates the following Content Security Policy directive: "script-src 'none'". Note that 'script-src-elem' was not explicitly set, so 'script-src' is used as a fallback.
PAGE LOG: [Report Only] Refused to load the script '***/extra-locales/overrides?v=cd2de844156e5af9515767b555160f84' because it violates the following Content Security Policy directive: "script-src 'none'". Note that 'script-src-elem' was not explicitly set, so 'script-src' is used as a fallback.
PAGE LOG: [Report Only] Refused to load the script '***/theme-javascripts/e182af2f9666cabcc7c497eea7a5c480af6ae643.js?__ws=linux.do' because it violates the following Content Security Policy directive: "script-src 'none'". Note that 'script-src-elem' was not explicitly set, so 'script-src' is used as a fallback.
PAGE LOG: [Report Only] Refused to load the script '***/theme-javascripts/50b626965055ed990042741b8be5b1d4772c70a9.js?__ws=linux.do' because it violates the following Content Security Policy directive: "script-src 'none'". Note that 'script-src-elem' was not explicitly set, so 'script-src' is used as a fallback.
PAGE LOG: [Report Only] Refused to load the script '***/theme-javascripts/581266d8811b6da8ca0fb9d5502efc7db231b15a.js?__ws=linux.do' because it violates the following Content Security Policy directive: "script-src 'none'". Note that 'script-src-elem' was not explicitly set, so 'script-src' is used as a fallback.
PAGE LOG: [Report Only] Refused to load the script '***/theme-javascripts/9fe41d69cb6ee099ca2554bcd2b0ecf6e4f8f70e.js?__ws=linux.do' because it violates the following Content Security Policy directive: "script-src 'none'". Note that 'script-src-elem' was not explicitly set, so 'script-src' is used as a fallback.
PAGE LOG: [Report Only] Refused to load the script '***/theme-javascripts/eb24783171e4cc70eb92d6479bd33133b3469ac8.js?__ws=linux.do' because it violates the following Content Security Policy directive: "script-src 'none'". Note that 'script-src-elem' was not explicitly set, so 'script-src' is used as a fallback.
PAGE LOG: [Report Only] Refused to load the script '***/theme-javascripts/815f07bab2a98d8fb3be14699bc210a1c58370f8.js?__ws=linux.do' because it violates the following Content Security Policy directive: "script-src 'none'". Note that 'script-src-elem' was not explicitly set, so 'script-src' is used as a fallback.
PAGE LOG: [Report Only] Refused to load the script '***/theme-javascripts/b95f7a5b225d2a5f5fa4e274086f861018a703c7.js?__ws=linux.do' because it violates the following Content Security Policy directive: "script-src 'none'". Note that 'script-src-elem' was not explicitly set, so 'script-src' is used as a fallback.
PAGE LOG: [Report Only] Refused to load the script '***/theme-javascripts/b3b3b2f1b332a617d66f58e8ae11eec31f2a0142.js?__ws=linux.do' because it violates the following Content Security Policy directive: "script-src 'none'". Note that 'script-src-elem' was not explicitly set, so 'script-src' is used as a fallback.
PAGE LOG: [Report Only] Refused to load the script '***/theme-javascripts/399d629c8b2c66a53d77bd3573ca85ac705e30cc.js?__ws=linux.do' because it violates the following Content Security Policy directive: "script-src 'none'". Note that 'script-src-elem' was not explicitly set, so 'script-src' is used as a fallback.
PAGE LOG: [Report Only] Refused to load the script '***/theme-javascripts/fdbcc8103e431b596978a97870873d142ccd08cb.js?__ws=linux.do' because it violates the following Content Security Policy directive: "script-src 'none'". Note that 'script-src-elem' was not explicitly set, so 'script-src' is used as a fallback.
PAGE LOG: [Report Only] Refused to load the script '***/theme-javascripts/cbefa0e50ddfeda09c9f832ffad12b80afaf6079.js?__ws=linux.do' because it violates the following Content Security Policy directive: "script-src 'none'". Note that 'script-src-elem' was not explicitly set, so 'script-src' is used as a fallback.
PAGE LOG: [Report Only] Refused to load the script '***/theme-javascripts/4f8d7c1edd15566e0db4d8a783fea78b6112cdc1.js?__ws=linux.do' because it violates the following Content Security Policy directive: "script-src 'none'". Note that 'script-src-elem' was not explicitly set, so 'script-src' is used as a fallback.
PAGE LOG: [Report Only] Refused to load the script '***/theme-javascripts/6768fbc0cf9b210666f0c0b42be26f7a8a30c80a.js?__ws=linux.do' because it violates the following Content Security Policy directive: "script-src 'none'". Note that 'script-src-elem' was not explicitly set, so 'script-src' is used as a fallback.
PAGE LOG: [Report Only] Refused to load the script '***/theme-javascripts/6e78b9756b2134d79adbda29e93b2165209e781d.js?__ws=linux.do' because it violates the following Content Security Policy directive: "script-src 'none'". Note that 'script-src-elem' was not explicitly set, so 'script-src' is used as a fallback.
PAGE LOG: [Report Only] Refused to load the script 'https://www.googletagmanager.com/gtag/js?id=G-1X49KS6K0M' because it violates the following Content Security Policy directive: "script-src 'none'". Note that 'script-src-elem' was not explicitly set, so 'script-src' is used as a fallback.
PAGE LOG: [Report Only] Refused to load the script '***/assets/google-universal-analytics-v4-e154af4adb3c483a3aba7f9a7229b8881cdc5cf369290923d965a2ad30163ae8.js' because it violates the following Content Security Policy directive: "script-src 'none'". Note that 'script-src-elem' was not explicitly set, so 'script-src' is used as a fallback.
PAGE LOG: [Report Only] Refused to execute inline script because it violates the following Content Security Policy directive: "script-src 'none'". Either the 'unsafe-inline' keyword, a hash ('sha256-6eXsxmck/y5Lc3XKIoiQtWavO3j4Rwqtfq51tYtZY5Y='), or a nonce ('nonce-...') is required to enable inline execution.
PAGE LOG: [Report Only] Refused to load the script '***/assets/start-discourse-9f921142b762fb91207051d0a28e571b9455bab74e7d0e03726024c286cff8d5.js' because it violates the following Content Security Policy directive: "script-src 'none'". Note that 'script-src-elem' was not explicitly set, so 'script-src' is used as a fallback.
PAGE LOG: [Report Only] Refused to load the script '***/assets/browser-update-6f90b23ab8d8bbdca5b58f8c616b7779f50c1315575c80eacccbc30e8bb3c32e.js' because it violates the following Content Security Policy directive: "script-src 'none'". Note that 'script-src-elem' was not explicitly set, so 'script-src' is used as a fallback.
PAGE LOG: [Report Only] Refused to execute inline script because it violates the following Content Security Policy directive: "script-src 'none'". Either the 'unsafe-inline' keyword, a hash ('sha256-QFlnYO2Ll+rgFRKkUmtyRublBc7KFNsbzF7BzoCqjgA='), or a nonce ('nonce-...') is required to enable inline execution.
PAGE LOG: [Report Only] Refused to load the script 'https://static.cloudflareinsights.com/beacon.min.js/vcd15cbe7772f49c399c6a5babf22c1241717689176015' because it violates the following Content Security Policy directive: "script-src 'none'". Note that 'script-src-elem' was not explicitly set, so 'script-src' is used as a fallback.
PAGE LOG: ℹ️ Discourse v3.3.0 — https://github.com/discourse/discourse/commits/ac30a798f0 — Ember v5.5.0
PAGE LOG: [Report Only] Refused to create a worker from '***/service-worker.js' because it violates the following Content Security Policy directive: "script-src 'none'". Note that 'worker-src' was not explicitly set, so 'script-src' is used as a fallback.
PAGE LOG: [Report Only] Refused to load the script '***/svg-sprite/linux.do/svg-1-f7379023b3863b9ac0a7d86b407aa426444facfd.js' because it violates the following Content Security Policy directive: "script-src 'none'". Note that 'script-src-elem' was not explicitly set, so 'script-src' is used as a fallback.
PAGE LOG: 脚本非第一次运行
PAGE LOG: autoRead true autoLikeEnabled false
PAGE LOG: 正在导航到下一个话题
Page error: Failed to execute 'getValue' on 'CookieDeprecationLabel': Illegal invocation
PAGE LOG: Found link: ***/t/topic/[17](https://github.com/fengyaocheng/auto-read-liunxdo/actions/runs/10284825125/job/28461687764#step:6:18)1984/536
PAGE LOG: 当前BASE_URL是: ***
PAGE LOG: 脚本正在运行在: ***
PAGE LOG: Initial clickCounter: 13
PAGE LOG: ℹ️ Discourse v3.3.0 — https://github.com/discourse/discourse/commits/ac30a798f0 — Ember v5.5.0
Page error: Failed to execute 'getValue' on 'CookieDeprecationLabel': Illegal invocation
PAGE LOG: 脚本非第一次运行
PAGE LOG: autoRead true autoLikeEnabled false
PAGE LOG: 执行正常的滚动和检查逻辑

**Comment by 14790897** [comment]
不影响
