### ISSUE TITLE
workflow执行一直报错

### ISSUE THREAD

**Issue by jiashu1024** [14790897/auto-read-liunxdo#47]
<img width="916" alt="image" src="https://github.com/user-attachments/assets/da08d0b6-fc2b-49a9-937b-0790e4c9c625">
环境变量如下，website是linuxdo
<img width="950" alt="image" src="https://github.com/user-attachments/assets/5275013f-acf1-4fd2-85fb-185a6b49cf68">

**Comment by jiashu1024** [comment]
<img width="960" alt="image" src="https://github.com/user-attachments/assets/e3087852-374c-47d2-bfb5-9dff11971bba">
登录日志

**Comment by 14790897** [comment]
这个属于正常情况😍😁，论坛自身的报错

**Comment by jiashu1024** [comment]
> 这个属于正常情况😍😁，论坛自身的报错
好咧，发现了。看到数据增长了。牛哇牛哇
