### ISSUE TITLE
可能始皇出手了吧(淚目

### ISSUE THREAD

**Issue by 123hi123** [14790897/auto-read-liunxdo#51]
![image](https://github.com/user-attachments/assets/19cdaebe-4a15-41c5-86d4-fed963cdefaa)
如圖
可以發現大概沒幾次就被鎖了
然後我用呃別人的一個腳本去查看我的閱讀帖子的數量
然後就發現呃，好像執行完腳本之後過一段時間的閱讀都不會算數

**Comment by 14790897** [comment]
啥玩意？

**Comment by 123hi123** [comment]
> 啥玩意？
抱歉，那個 enter 按太快

**Comment by 14790897** [comment]
阅读量要过一段时间才会显示，这个正常，可以用

**Comment by 123hi123** [comment]
啊 所以他那邊錯也是有成功閱讀到的意思哦

**Comment by 14790897** [comment]
是的，不放心的话，可以在本地Windows上运行进行测试，会展示图形化界面的运行过程

**Comment by 123hi123** [comment]
![image](https://github.com/user-attachments/assets/492964d1-c52e-499a-8a86-0ed869018e9c)
有料哎
升三級。呃，如果我還記得的話，我一定要標你

**Comment by 123hi123** [comment]
> 是的，不放心的话，可以在本地Windows上运行进行测试，会展示图形化界面的运行过程

忘記問 你是指我不放心什麼

**Comment by 14790897** [comment]
不放心脚本有没有正常运行
