### ISSUE TITLE
老 是不是被鎖ip了 還是這個還有用

### ISSUE THREAD

**Issue by 123hi123** [14790897/auto-read-liunxdo#52]
![Screenshot_20240908-124721.png](https://github.com/user-attachments/assets/19282ef3-5cdd-4766-af0b-e0dea8be9ab7)

**Comment by 14790897** [comment]
能用的，报什么错

**Comment by 14790897** [comment]
。。。

**Comment by 123hi123** [comment]
所以那個x是我的幻像對吧

**Comment by 123hi123** [comment]
其實是能用的 
謝老解說

**Comment by 14790897** [comment]
> 所以那個x是我的幻像對吧

![image](https://github.com/user-attachments/assets/f50a6fac-600a-4f50-98a1-0cdd6157e65c)
不是你的幻想，但是你要点击这一行然后看到具体的报错，再给我报错信息

**Comment by 123hi123** [comment]
> > 所以那個x是我的幻像對吧
> 
> ![image](https://private-user-images.githubusercontent.com/121866954/365438172-f50a6fac-600a-4f50-98a1-0cdd6157e65c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU4NjM5MjMsIm5iZiI6MTcyNTg2MzYyMywicGF0aCI6Ii8xMjE4NjY5NTQvMzY1NDM4MTcyLWY1MGE2ZmFjLTYwMGEtNGY1MC05OGExLTBjZGQ2MTU3ZTY1Yy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkwOVQwNjMzNDNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02OGMyN2RkNTQ2ODVhZDg4NWExZGFjN2YxZGNlODQzMmJlZmEyOTc3MTRiM2JhMDhkZWExYTRlM2RlM2MxYjM2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.tub3oMrHd7tuf3rYnSngwpMOLsLgTpJf0xFMI1gCrA8) 不是你的幻想，但是你要点击这一行然后看到具体的报错，再给我报错信息

![image](https://github.com/user-attachments/assets/3c562f9c-656e-4a19-8fcf-73642c4180c7)

**Comment by 14790897** [comment]
> > > 所以那個x是我的幻像對吧
> > 
> > 
> > ![image](https://private-user-images.githubusercontent.com/121866954/365438172-f50a6fac-600a-4f50-98a1-0cdd6157e65c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU4NjM5MjMsIm5iZiI6MTcyNTg2MzYyMywicGF0aCI6Ii8xMjE4NjY5NTQvMzY1NDM4MTcyLWY1MGE2ZmFjLTYwMGEtNGY1MC05OGExLTBjZGQ2MTU3ZTY1Yy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkwOVQwNjMzNDNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02OGMyN2RkNTQ2ODVhZDg4NWExZGFjN2YxZGNlODQzMmJlZmEyOTc3MTRiM2JhMDhkZWExYTRlM2RlM2MxYjM2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.tub3oMrHd7tuf3rYnSngwpMOLsLgTpJf0xFMI1gCrA8) 不是你的幻想，但是你要点击这一行然后看到具体的报错，再给我报错信息
> 
> ![image](https://private-user-images.githubusercontent.com/36217117/365536432-3c562f9c-656e-4a19-8fcf-73642c4180c7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU4NjcwNDYsIm5iZiI6MTcyNTg2Njc0NiwicGF0aCI6Ii8zNjIxNzExNy8zNjU1MzY0MzItM2M1NjJmOWMtNjU2ZS00YTE5LThmY2YtNzM2NDJjNDE4MGM3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTA5VDA3MjU0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgwNTJkNjk5ZmMyZDc0MmUzMmFlZTczOWI0NTNjZmJkMGNjNTViNzdkNDc4NjM4MmE5ODgzMzUyMWRlYjZjM2UmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.bW1d_EW-KjvmiEM5Wn8gFfAP5wynOzXqH9fW2iAczgs)

这个是运行正常的
