### ISSUE TITLE
action跑不过去，一直报错密码错误

### ISSUE THREAD

**Issue by shxiq01** [14790897/auto-read-liunxdo#58]
![image](https://github.com/user-attachments/assets/59186dfe-6db2-413d-926b-395e2c9766c1)
![image](https://github.com/user-attachments/assets/9b6ab7cf-ff50-4acd-a73a-8ce5f531ae2c)

佬 能帮忙看下问题吗？密码带了双引号，是什么原因呢？

**Comment by 14790897** [comment]
别带双引号

**Comment by shxiq01** [comment]
> 别带双引号

啊 可以了  原来是这样  tks
