### ISSUE TITLE
这算运行成功了吗

### ISSUE THREAD

**Issue by ericsgit2** [14790897/auto-read-liunxdo#6]
[Code](https://github.com/ericsgit2/auto-read-liunxdo)
[Pull requests](https://github.com/ericsgit2/auto-read-liunxdo/pulls)
[Scheduled Node.js CI](https://github.com/ericsgit2/auto-read-liunxdo/actions/workflows/cron_read.yaml)
Scheduled Node.js CI #2
build (20.x)
Started 2m 52s ago
Beta
Give feedback
1s
0s
3s
12s
2m 37s
Run node pteer.js
PAGE LOG: ℹ️ Discourse v3.2.1 — https://github.com/discourse/discourse/commits/5abd8e9bb0 — Ember v5.5.0
PAGE LOG: [DOM] Input elements should have autocomplete attributes (suggested: "current-password"): (More info: https://goo.gl/9p2vKq) %o
登录操作
PAGE LOG: JSHandle@node
PAGE LOG: Login button clicked.
PAGE LOG: Autofocus processing was blocked because a document already has a focused element.
PAGE LOG: ℹ️ Discourse v3.2.[1](https://github.com/ericsgit2/auto-read-liunxdo/actions/runs/8571131277/job/23490690522#step:5:1) — https://github.com/discourse/discourse/commits/5abd8e9bb0 — Ember v5.5.0
找到avatarImg，登录成功
Page error: Cannot read properties of null (reading 'appendChild')
PAGE LOG: ℹ️ Discourse v3.2.1 — https://github.com/discourse/discourse/commits/5abd8e9bb0 — Ember v5.5.0
PAGE LOG: 脚本第一次运行，执行初始化操作...
PAGE LOG: 执行了初始数据更新操作
PAGE LOG: autoRead true autoLikeEnabled true
PAGE LOG: 执行正常的滚动和检查逻辑
PAGE LOG: 已滚动到底部
Page error: Cannot read properties of null (reading 'appendChild')
PAGE LOG: ℹ️ Discourse v3.2.1 — https://github.com/discourse/discourse/commits/5abd8e9bb0 — Ember v5.5.0
PAGE LOG: 脚本非第一次运行
PAGE LOG: autoRead true autoLikeEnabled true
PAGE LOG: 正在导航到下一个话题
PAGE LOG: Found link: https://linux.do/t/topic/48228/4
Page error: Cannot read properties of null (reading 'appendChild')
PAGE LOG: ℹ️ Discourse v3.2.1 — https://github.com/discourse/discourse/commits/5abd8e9bb0 — Ember v5.5.0
PAGE LOG: 脚本非第一次运行
PAGE LOG: autoRead true autoLikeEnabled true
PAGE LOG: 执行正常的滚动和检查逻辑
PAGE LOG: Clicked like button 1
PAGE LOG: Clicked like button 2
PAGE LOG: Clicked like button 3
PAGE LOG: Clicked like button 4
PAGE LOG: Clicked like button 5
PAGE LOG: Clicked like button 6
PAGE LOG: Clicked like button [7](https://github.com/ericsgit2/auto-read-liunxdo/actions/runs/8571131277/job/23490690522#step:5:8)
PAGE LOG: Clicked like button 8
PAGE LOG: Clicked like button 9
PAGE LOG: Clicked like button 10
PAGE LOG: Failed to load resource: the server responded with a status of 429 ()
PAGE LOG: Failed to update topic times for topic 48228 due to 429 error
PAGE LOG: Clicked like button 11
PAGE LOG: 已滚动到底部
PAGE LOG: Failed to load resource: the server responded with a status of 429 ()
PAGE LOG: Failed to load resource: the server responded with a status of 429 ()
Page error: Failed to read the 'localStorage' property from 'Window': Access is denied for this document.
Page error: Failed to read the 'localStorage' property from 'Window': Access is denied for this document.
Page error: Failed to read the 'localStorage' property from 'Window': Access is denied for this document.
Retrying now...
Page error: Cannot read properties of null (reading 'appendChild')
PAGE LOG: ℹ️ Discourse v3.2.1 — https://github.com/discourse/discourse/commits/5abd8e9bb0 — Ember v5.5.0
PAGE LOG: 脚本非第一次运行
PAGE LOG: autoRead true autoLikeEnabled false
PAGE LOG: 正在导航到下一个话题
PAGE LOG: Found link: https://linux.do/t/topic/47799/5
Page error: Cannot read properties of null (reading 'appendChild')
PAGE LOG: ℹ️ Discourse v3.2.1 — https://github.com/discourse/discourse/commits/5abd[8](https://github.com/ericsgit2/auto-read-liunxdo/actions/runs/8571131277/job/23490690522#step:5:9)e9bb0 — Ember v5.5.0
PAGE LOG: 脚本非第一次运行
PAGE LOG: autoRead true autoLikeEnabled false
PAGE LOG: 执行正常的滚动和检查逻辑
PAGE LOG: 已滚动到底部
Page error: Cannot read properties of null (reading 'appendChild')
PAGE LOG: ℹ️ Discourse v3.2.1 — https://github.com/discourse/discourse/commits/5abd8e[9](https://github.com/ericsgit2/auto-read-liunxdo/actions/runs/8571131277/job/23490690522#step:5:10)bb0 — Ember v5.5.0
PAGE LOG: 脚本非第一次运行
PAGE LOG: autoRead true autoLikeEnabled false
PAGE LOG: 正在导航到下一个话题
PAGE LOG: Found link: https://linux.do/t/topic/37675/459
Page error: Cannot read properties of null (reading 'appendChild')
PAGE LOG: ℹ️ Discourse v3.2.1 — https://github.com/discourse/discourse/commits/5abd8e9bb0 — Ember v5.5.0
PAGE LOG: 脚本非第一次运行
PAGE LOG: autoRead true autoLikeEnabled false
PAGE LOG: 执行正常的滚动和检查逻辑
PAGE LOG: 已滚动到底部
Page error: Cannot read properties of null (reading 'appendChild')
PAGE LOG: ℹ️ Discourse v3.2.1 — https://github.com/discourse/discourse/commits/5abd8e9bb0 — Ember v5.5.0
PAGE LOG: 脚本非第一次运行
PAGE LOG: autoRead true autoLikeEnabled false
PAGE LOG: 正在导航到下一个话题
PAGE LOG: Found link: https://linux.do/t/topic/48[12](https://github.com/ericsgit2/auto-read-liunxdo/actions/runs/8571131277/job/23490690522#step:5:13)9/34
Page error: Cannot read properties of null (reading 'appendChild')
PAGE LOG: ℹ️ Discourse v3.2.1 — https://github.com/discourse/discourse/commits/5abd8e9bb0 — Ember v5.5.0
PAGE LOG: 脚本非第一次运行
PAGE LOG: autoRead true autoLikeEnabled false
PAGE LOG: 执行正常的滚动和检查逻辑
PAGE LOG: 已滚动到底部
Page error: Cannot read properties of null (reading 'appendChild')
PAGE LOG: ℹ️ Discourse v3.2.1 — https://github.com/discourse/discourse/commits/5abd8e9bb0 — Ember v5.5.0
PAGE LOG: 脚本非第一次运行
PAGE LOG: autoRead true autoLikeEnabled false
PAGE LOG: 正在导航到下一个话题
PAGE LOG: Found link: https://linux.do/t/topic/47930/39
Page error: Cannot read properties of null (reading 'appendChild')
PAGE LOG: ℹ️ Discourse v3.2.1 — https://github.com/discourse/discourse/commits/5abd8e9bb0 — Ember v5.5.0
PAGE LOG: 脚本非第一次运行
PAGE LOG: autoRead true autoLikeEnabled false
PAGE LOG: 执行正常的滚动和检查逻辑
PAGE LOG: 已滚动到底部
Page error: Cannot read properties of null (reading 'appendChild')
PAGE LOG: ℹ️ Discourse v3.2.1 — https://github.com/discourse/discourse/commits/5abd8e9bb0 — Ember v5.5.0
PAGE LOG: 脚本非第一次运行
PAGE LOG: autoRead true autoLikeEnabled false
PAGE LOG: 正在导航到下一个话题
PAGE LOG: Found link: https://linux.do/t/topic/48267/7
Page error: Cannot read properties of null (reading 'appendChild')
PAGE LOG: ℹ️ Discourse v3.2.1 — https://github.com/discourse/discourse/commits/5abd8e9bb0 — Ember v5.5.0
PAGE LOG: 脚本非第一次运行
PAGE LOG: autoRead true autoLikeEnabled false
PAGE LOG: 执行正常的滚动和检查逻辑
PAGE LOG: 已滚动到底部
Page error: Cannot read properties of null (reading 'appendChild')
PAGE LOG: ℹ️ Discourse v3.2.1 — https://github.com/discourse/discourse/commits/5abd8e9bb0 — Ember v5.5.0
PAGE LOG: 脚本非第一次运行
PAGE LOG: autoRead true autoLikeEnabled false
PAGE LOG: 正在导航到下一个话题
PAGE LOG: Found link: https://linux.do/t/topic/174[13](https://github.com/ericsgit2/auto-read-liunxdo/actions/runs/8571131277/job/23490690522#step:5:14)/935
Page error: Cannot read properties of null (reading 'appendChild')
PAGE LOG: ℹ️ Discourse v3.2.1 — https://github.com/discourse/discourse/commits/5abd8e9bb0 — Ember v5.5.0
PAGE LOG: 脚本非第一次运行
PAGE LOG: autoRead true autoLikeEnabled false
PAGE LOG: 执行正常的滚动和检查逻辑
PAGE LOG: 已滚动到底部
Page error: Cannot read properties of null (reading 'appendChild')
PAGE LOG: ℹ️ Discourse v3.2.1 — https://github.com/discourse/discourse/commits/5abd8e9bb0 — Ember v5.5.0
PAGE LOG: 脚本非第一次运行
PAGE LOG: autoRead true autoLikeEnabled false
PAGE LOG: 正在导航到下一个话题
PAGE LOG: Found link: https://linux.do/t/topic/48127
Page error: Cannot read properties of null (reading 'appendChild')
PAGE LOG: ℹ️ Discourse v3.2.1 — https://github.com/discourse/discourse/commits/5abd8e9bb0 — Ember v5.5.0
PAGE LOG: 脚本非第一次运行
PAGE LOG: autoRead true autoLikeEnabled false
PAGE LOG: 执行正常的滚动和检查逻辑
PAGE LOG: 已滚动到底部
Page error: Cannot read properties of null (reading 'appendChild')
PAGE LOG: ℹ️ Discourse v3.2.1 — https://github.com/discourse/discourse/commits/5abd8e9bb0 — Ember v5.5.0
PAGE LOG: 脚本非第一次运行
PAGE LOG: autoRead true autoLikeEnabled false
PAGE LOG: 正在导航到下一个话题
PAGE LOG: Found link: https://linux.do/t/topic/[17](https://github.com/ericsgit2/auto-read-liunxdo/actions/runs/8571131277/job/23490690522#step:5:18)413/1
Page error: Cannot read properties of null (reading 'appendChild')
PAGE LOG: ℹ️ Discourse v3.2.1 — https://github.com/discourse/discourse/commits/5abd8e9bb0 — Ember v5.5.0
PAGE LOG: 脚本非第一次运行
PAGE LOG: autoRead true autoLikeEnabled false
PAGE LOG: 执行正常的滚动和检查逻辑

**Comment by 14790897** [comment]
成功了

**Comment by 14790897** [comment]
😍

**Comment by ericsgit2** [comment]
429之类报错不用管吗 似乎需要手动stop Action才停止运行
