### ISSUE TITLE
日志里为啥也有https://meta.discourse.org？

### ISSUE THREAD

**Issue by anunol** [14790897/auto-read-liunxdo#67]
为什么运行日志内除了L站，还有https://meta.discourse.org，难不成使用相同的账号密码区Meta社区也去登录尝试？

**Comment by 14790897** [comment]
这个问题比较难解决，可能是puppeteer启动了两次，功能还是正常的，只阅读选定的网站，没有阅读https://meta.discourse.orghttps://meta.discourse.org
