### ISSUE TITLE
这个状态是不是运行异常的

### ISSUE THREAD

**Issue by lostme01** [14790897/auto-read-liunxdo#8]
![image](https://github.com/14790897/auto-read-liunxdo/assets/28937468/4c78ac7c-36e3-424c-bfd0-11dba2cba57f)

**Comment by lostme01** [comment]
没成功

**Comment by 14790897** [comment]
前面的输出截图给我看看。

**Comment by lostme01** [comment]
一开始是有登录和阅读的，后来就有429还有这个了，一会我给你找找发出来

**Comment by 14790897** [comment]
运行正常的
