### ISSUE TITLE
retrying now...

### ISSUE THREAD

**Issue by dinaau** [14790897/auto-read-liunxdo#82]
用的github action 显示
一直卡在retrying now， 是不是哪里配置的问题？

Run node bypasscf.js --USERNAMES "$USERNAMES" --PASSWORDS "$PASSWORDS" --WEBSITE "$WEBSITE"
node bypasscf.js --USERNAMES "$USERNAMES" --PASSWORDS "$PASSWORDS" --WEBSITE "$WEBSITE"
shell: /usr/bin/bash -e {0}
env:
USERNAMES: ***
PASSWORDS: ***
RUN_TIME_LIMIT_MINUTES: ***
TELEGRAM_BOT_TOKEN:
TELEGRAM_CHAT_ID:
WEBSITE: ***
Using .env file to supply config environment variables, you can create a .env.local file to overwrite defaults, it doesn't upload to git
运行时间限制为：*** 分钟 ([2](https://github.com/dinaau/auto-read-linux.do/actions/runs/12509192074/job/34898325395#step:6:2)100000 毫秒)
当前批次：1 - 4
Health check endpoint is running at http://localhost:8081/health
当前用户: a
页面标题： LINUX DO - 新的理想型社区
当前用户: b
登录操作
页面标题： LINUX DO - 新的理想型社区
找到avatarImg，登录成功
登录操作
找到avatarImg，登录成功
等待 2[10](https://github.com/dinaau/auto-read-linux.do/actions/runs/12509192074/job/34898325395#step:6:10)0 秒
Retrying now...
Retrying now...

**Comment by 14790897** [comment]
正常

**Comment by 14790897** [comment]
现在不会输出日志了

**Comment by 14790897** [comment]
那个是你自己取消的

dinaau ***@***.***> 于 2024年12月27日周五 上午11:40写道：

**Comment by 14790897** [comment]
人为操作导致的

**Comment by 14790897** [comment]
已解决

**Comment by JoeNik** [comment]
> 也正

现在是都没有输出日志了啊？？？我还以为不能用呢
